### ISSUE TITLE
Prepare for Docker

### ISSUE THREAD

**Issue by olivierberthomme** [DewGew/Domoticz-Google-Assistant#105]
**Makes for project more compliant to Docker containers**

**Proposal**
Change location of config.yaml + smart-home-key.json files to something like "/config" folder (instead of root directory).
With that, you should configure a "volume" (persistant data) for this folder and save custom files.

**Tested & functionnal dockerfile**
```FROM jfloff/alpine-python:3.7-slim
 
# Update Software repository
RUN apk add --update --no-cache git

ARG COMMIT_ID
RUN cd / && \
    git clone https://github.com/DewGew/Domoticz-Google-Assistant && \
    cp ./Domoticz-Google-Assistant/requirements/pip-requirements.txt requirements.txt

#Copy configuration
COPY apk-requirements.txt apk-requirements.txt
COPY config.yaml /Domoticz-Google-Assistant/config.yaml
COPY smart-home-key.json /Domoticz-Google-Assistant/smart-home-key.json
 
# Configure Services and Port
CMD ["python3 Domoticz-Google-Assistant"]
 
EXPOSE 3030
```

With apk-requirements.txt file:
```
python3
python3-dev
gcc
musl-dev
libffi-dev
libressl-dev
git
```

**Comment by DewGew** [comment]
Creat suggestion but  I dont use docker.  Is it possible to use system-requirements.txt instead of third text file. Maybe add docker specifike apk in the docker file?

**Comment by DewGew** [comment]
> With that, you should configure a "volume" (persistant data) for this folder and save custom files.

How do you mean with this? change from root dir to /config I get :)

**Comment by DewGew** [comment]
See beta branch. Changed the config.yaml and smart-home-key.json path to /config
https://github.com/DewGew/Domoticz-Google-Assistant/commit/76da25a4ff9dcc0a5825a692ee3a3bdccd994443

**Comment by olivierberthomme** [comment]
#107 works like a charm! I vote for a merge into master.
I also get in touch with LinuxServer.io's team to ask if you project could match their Docker images setup. Maybe, they will setup a workflow to automate the docker image creation for your project.

**Comment by DewGew** [comment]
Added Dockerfile:
```
# Dockerfile for Domoticz-Google-Assistant

# Install minimal Python 3.
FROM jfloff/alpine-python:3.7-slim

# Install Software
RUN cd / && \
    apk add  --no-cache --virtual=build-dependencies \
                git \
                libffi-dev \
                libressl-dev && \
    git clone https://github.com/DewGew/Domoticz-Google-Assistant.git dzGA && \
    cp /dzGA/requirements/pip-requirements.txt /requirements.txt

# Create volume
VOLUME /dzGA/config

# Configure Services and Port
CMD ["python3 /dzGA/__main__.py"]

EXPOSE 3030
```
Docker build works fine.

Added docker.compose.yaml:
```
version: '3'
services:
  dz-googleassistant:
    build: '.'
    image: domoticz-google-assistant
    container_name: domoticz-google-assistant
    environment:
      - PUID=1010
      - PGID=1010
    ports:
      - 3030:3030
    volumes:
      - /home/${USER}/Domoticz-Google-Assistant/config:/dzGA/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
```
Works great for ubuntu/raspberry pi.
